#!/bin/bash

THIS_SCRIPT="$0"
# Service status is written to file, to survive reboot.
DEFAULT='/etc/default/srv-raspistill'
if [ ! -f "$DEFAULT" ] || ! grep -q '^ENABLED=' "$DEFAULT"; then
    echo -e '\nENABLED=0' | sudo tee --append "$DEFAULT" > /dev/null
fi

case "$1" in
    start)
        grep -q '^ENABLED=1\b' "$DEFAULT" || sudo sed -i -- 's/^ENABLED=.*/ENABLED=1/' "$DEFAULT"
        if "$THIS_SCRIPT" status > /dev/null; then
            sudo /usr/local/lib/rpi-explorer-kit/daemonize-raspistill &
        else
            echo "raspistill already running"
        fi
        ;;
    stop)
        grep -q '^ENABLED=0\b' "$DEFAULT" || sudo sed -i -- 's/^ENABLED=.*/ENABLED=0/' "$DEFAULT"
        sudo killall --quiet raspistill
        ;;
    status)
        PID="$(ps uax | grep '/usr/bin/raspistill' | grep -v grep | head -n 1 | awk '{print $2}')"
        if [ -z "$PID" ]; then
            echo "stopped"
            exit 0
        else
            if (cat /proc/$PID/cmdline | grep -q '^/usr/bin/raspistill'); then
                echo "started"
                exit 1
            else
                echo "unknown"
                exit 2
            fi
        fi
        ;;
    *)
        echo "Usage: $0 {start|stop|status}"
        ;;
esac
exit 0
