#!/bin/bash

case "$1" in
    start)
        sudo /usr/local/lib/rpi-explorer-kit/daemonize-reboot &
        ;;
    status)
        echo "unknown"
        exit 2
        ;;
    *)
        echo "Usage: $0 {start|status}"
        ;;
esac
exit 0
